theme: jekyll-theme-cayman
title: codétude 
author: jagatpanchal22  
email: jagtpanchal22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  étude meaning learning or study. its a french work. based on this we found one word codétude
  it means co-study but here we're learning technologies, programming stuff so we consider this word as 
  code-learning. 
# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
